---
title: "P8105 Homework 6"
author: "Yeyi Zhang, yz3300"
---
Hello! This is a website for data science homework 6!  
I worked with Huijuan Zhang (UNI: hz2510) for this homework.

In this homework, we used __Instacart__ dataset. 

First, read data and clean names.

Then, in the dashboard we created two columns. In the first column, we put a violin plot that describes the distribution of the hour of the day on which the order was placed in different departments. In the column on the right, we put a boxplot and a histogram. Boxplot shows days since the last order for each department and the histogram is the distribution of order hour of day.

Last, in the dashboard for shiny app, we made little changes on each plot and created a side bar that contain a selection of departments, selection range of order hours and order choices (wether the items being reordered or not).

## Links
Dashboard from Problem 1 is [here](problem1/problem1.html).


Dashboard from Problem 2 is [here](https://huijuanzhang.shinyapps.io/p8105_hw6_problem2/).


The GitHub repos for this problem are [Problem 1](https://github.com/HuijuanZhang/p8105_hw6_p1),
[Problem 2](https://github.com/zyy7348/p8105_hw6_problem2) and [Website](https://github.com/zyy7348/p8105_hw6_yz3300.github.io).




